version: '2'

services:

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - rubyapp1:rubyapp1
      - rubyapp2:rubyapp2

  rubyapp1:
    build: ./app
    expose:
      - "4567"
    depends_on:
      - redis
    links:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  rubyapp2:
    build: ./app
    expose:
      - "4567"
    depends_on:
      - redis
    links:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:latest
    expose:
      - "6379"